module.exports = {
  1: { id: 1, name: 'Eastern Africa' },
  2: { id: 2, name: 'Middle Africa' },
  3: { id: 3, name: 'Northern Africa' },
  4: { id: 4, name: 'Southern Africa' },
  5: { id: 5, name: 'Western Africa' },
  7: { id: 7, name: 'Caribbean' },
  8: { id: 8, name: 'South America' },
  9: { id: 9, name: 'Central America' },
  10: { id: 10, name: 'Central Asia' },
  11: { id: 11, name: 'Eastern Asia' },
  12: { id: 12, name: 'Southern Asia' },
  13: { id: 13, name: 'South-Eastern Asia' },
  14: { id: 14, name: 'Western Asia' },
  15: { id: 15, name: 'Eastern Europe' },
  16: { id: 16, name: 'Nothern Europe' },
  17: { id: 17, name: 'Southern Europe' },
  18: { id: 18, name: 'Western Europe' },
  19: { id: 19, name: 'Australia & New Zealand' },
  20: { id: 20, name: 'Melanesia' },
  21: { id: 21, name: 'Micronesia' },
  22: { id: 22, name: 'Polynesia' },
  23: { id: 23, name: 'North America' },
};
